nodeLinker: node-modules
# unfortunately pnp mode breaks build-storybook
# https://github.com/storybookjs/storybook/issues/18801#issuecomment-1409734510
# https://yarnpkg.com/features/pnp
# we can't do zero-installs then
# https://yarnpkg.com/features/zero-installs
# this is an issue with story book and not yarn
# nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.3.1.cjs
